Remove one deprecated lib and propose another
arduino/library-registry pull request #2481
Opened 2023-02-16 05:41 UTC by mats-nk

Removed: https://github.com/JHershey69/weatherLocation-Library This is deprecated as Dark Sky is no longer in operation, from authors github description

Propose to add: https://github.com/Bodmer/OpenWeather This Lib uses the free API to OpenWeatherMap. The other "https://github.com/JHershey69/OpenWeatherOneCall" uses the PAY API to OpenWeatherMap.

2023-02-16 07:50 UTC, per1234 requested changes
Hi @mats-nk. We have a policy that libraries can only be removed by request from the maintainer, or in emergency cases with high level approval from Arduino.

So, even though it does seem clear that the library is no longer of value, I don't think I can approve the removal of the "**weatherLocation**" library unless I receive approval from @JHershey69

But anyone is welcome to submit any library, so it is fine if you want to submit the "**OpenWeather**" library.

If you would like to continue with the "**weatherLocation**" library removal attempt, then please submit a separate pull request for the "**OpenWeather**" library submission. Otherwise you can update this PR if you like.

2023-02-16 13:16 UTC, JHershey69 commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:DengXian;
	panose-1:2 1 6 0 3 1 1 1 1 1;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	***@***.***";
	panose-1:2 1 6 0 3 1 1 1 1 1;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
-->OPENWEATHERONECALL library clearly states “some actions require fees” and the current One Call 3.0 on OPENWEATHER is a subscription service but users get 1000 CALLS A DAY FOR FREE. Which is a weather call once every 15 minutes FOR FREE. The OPENWEATHERONECALL library provides historical weather, and other features not available in BODMER’s OpenWeather Library. Anyone looking for ONLY current weather are free to choose Bodmer’s library but this makes my library no less of a value to Arduino users. Thank you.   Sent from Mail for Windows From: per1234Sent: Thursday, February 16, 2023 2:51 AMTo: arduino/library-registryCc: Jessica Hershey; MentionSubject: Re: [arduino/library-registry] Remove one deprecated lib and propose another (PR ***@***.*** requested changes on this pull request.Hi @mats-nk. We have a policy that libraries can only be removed by request from the maintainer, or in emergency cases with high level approval from Arduino.So, even though it does seem clear that the library is no longer of value, I don't think I can approve the removal of the "weatherLocation" library unless I receive approval from @JHershey69But anyone is welcome to submit any library, so it is fine if you want to submit the "OpenWeather" library.If you would like to continue with the "weatherLocation" library removal attempt, then please submit a separate pull request for the "OpenWeather" library submission. Otherwise you can update this PR if you like.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***> Virus-free.www.avast.com

2023-02-16 14:53 UTC, per1234 commented
Hi @JHershey69. Thanks for your response. The primary focus of this discussion is your  "**weatherLocation**" library:

https://github.com/JHershey69/weatherLocation-Library

@mats-nk is proposing to remove it from Library Manager. As I explained above, Arduino will only remove libraries on request from the library maintainer. So the choice of whether the library will be removed is yours to make. I mentioned you in this discussion in case you might like to comment on that subject.

As for your "**OpenWeatherOneCall**" library, there is no proposal to remove it. The "**OpenWeatherOneCall**" library will remain in the Arduino Library Manager regardless of any decision that is made about the "**weatherLocation**" library.

2023-02-16 16:10 UTC, JHershey69 commented
WeatherLocation is clearly deprecated, has been since 2020 when Dark Sky closed. I mentioned OpenWeatherOneCall because it was referenced in the original request, and "Pay Subscription" used as defense for Bodmer's. Bodmer is friend, and has helped me a lot in other areas of the Arduino, and I know he has a library for Open Weather. If he wants it added to the library, I encourage such a move. I'll by him a drink when it propagates. lol. Competition spurs innovation.

2023-02-16 16:16 UTC, per1234 commented
>WeatherLocation is clearly deprecated, has been since 2020 when Dark Sky closed.

@JHershey69 do you approve the removal of [your "**weatherLocation**" library](https://github.com/JHershey69/weatherLocation-Library). Please make sure to format your reply so that there is no ambiguity.

2023-02-16 16:21 UTC, JHershey69 commented
I approve the removal of my "weatherLocation" library

(https://github.com/JHershey69/weatherLocation-Library).

2023-02-16 17:53 UTC, per1234 commented
OK, thanks!

2023-02-16 17:54 UTC, per1234 requested changes
@mats-nk. Please split this into two separate pull requests:

- remove "weatherLocation" library
- add "OpenWeather" library

Each of those operations is handled in a different way so they must be in separate pull requests.

2023-02-17 12:40 UTC, mats-nk commented
> @mats-nk. Please split this into two separate pull requests:
> 
>     * remove "weatherLocation" library
> 
>     * add "OpenWeather" library
> 
> 
> Each of those operations is handled in a different way so they must be in separate pull requests.

I will do!

2023-02-17 12:44 UTC, closed without merging

2023-02-17 12:44 UTC, mats-nk commented
Split

2023-02-17 13:03 UTC, per1234 commented
>I will keep one change = One ticket in the future, should have known better...

It is fine to combine multiple requests for the same type of operation (e.g., submit multiple libraries) in a single PR if you like. The system is designed to support that. It is only the combination of multiple types of operation (e.g., a submission and a removal) in a single PR that is problematic. But one PR per change is also perfectly fine.

>Split

Thanks! I see the PR to submit "**OpenWeather**" was already accepted, but I didn't see the PR for the removal of the "**weatherLocation**" library. Were you still planning to submit a PR for that @mats-nk?